[package]
name = "draper-core"
version.workspace = true
edition.workspace = true

[features]
default = []
serde = ["dep:serde", "dep:serde_json", "draper-geometry/serde", "draper-topology/serde", "draper-mesh/serde", "draper-step/serde"]

[dependencies]
draper-geometry = { workspace = true }
draper-topology = { workspace = true }
draper-mesh = { workspace = true, default-features = false }
draper-step = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
env_logger = { workspace = true }
