[package]
name = "draper-step"
version.workspace = true
edition.workspace = true

[features]
default = []
serde = ["dep:serde", "dep:serde_json", "draper-geometry/serde", "draper-topology/serde", "draper-mesh/serde"]

[dependencies]
draper-geometry = { workspace = true }
draper-topology = { workspace = true }
draper-mesh = { workspace = true, default-features = false }
earcutr = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
env_logger = "0.11"
quickcheck = { workspace = true }
quickcheck_macros = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "1"
