/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start: () => void;
export const __wbg_workerparseresult_free: (a: number, b: number) => void;
export const __wbg_workertriangulateresult_free: (a: number, b: number) => void;
export const worker_cancel: () => void;
export const worker_get_assembly_tree: () => [number, number];
export const worker_parse_step: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const worker_triangulate_brep: () => number;
export const workerparseresult_assembly_tree_json: (a: number) => [number, number];
export const workerparseresult_brep_count: (a: number) => number;
export const workerparseresult_entity_count: (a: number) => number;
export const workerparseresult_error: (a: number) => [number, number];
export const workerparseresult_face_count: (a: number) => number;
export const workerparseresult_pending_breps_json: (a: number) => [number, number];
export const workerparseresult_shell_count: (a: number) => number;
export const workertriangulateresult_brep_id: (a: number) => bigint;
export const workertriangulateresult_color: (a: number) => [number, number];
export const workertriangulateresult_colors: (a: number) => [number, number];
export const workertriangulateresult_error: (a: number) => [number, number];
export const workertriangulateresult_face_normals: (a: number) => [number, number];
export const workertriangulateresult_indices: (a: number) => [number, number];
export const workertriangulateresult_name: (a: number) => [number, number];
export const workertriangulateresult_normals: (a: number) => [number, number];
export const workertriangulateresult_remaining: (a: number) => number;
export const workertriangulateresult_vertices: (a: number) => [number, number];
export const main: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__h925e8d6377294b5d: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h02c6bc4fe7ddc8b1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hc904ec35267f910e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hc904ec35267f910e_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hbca3773cac796aac: (a: number, b: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
