// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 KernelDev
//! Web Worker for offloading STEP parsing and triangulation from the main thread.
//!
//! This worker runs the heavy computational tasks (STEP file parsing, B-Rep
//! triangulation, mesh generation) in a background thread, keeping the main
//! thread free for UI rendering at 60+ FPS.
//!
//! # Architecture
//!
//! Main Thread (UI):
//!   - Handles user input, egui/wgpu rendering
//!   - Sends STEP file content to worker via postMessage
//!   - Receives triangulated mesh data back via onmessage
//!
//! Worker Thread:
//!   - Initializes WASM module on startup
//!   - Parses STEP files into B-Rep topology
//!   - Triangulates B-Reps one at a time
//!   - Sends completed mesh vertices/indices back to main thread
//!
//! # Message Protocol
//!
//! Main → Worker:
//!   { type: "init" }                           — Initialize WASM (auto-sent on worker start)
//!   { type: "parse", id, content, name, lod, is_mobile } — Parse STEP file content
//!   { type: "triangulate_next", id }           — Triangulate next pending BREP
//!   { type: "cancel" }                         — Cancel current processing
//!   { type: "get_structure", id }              — Get assembly structure tree
//!
//! Worker → Main:
//!   { type: "ready" }                          — Worker initialized and ready
//!   { type: "parse_complete", id, stats }      — STEP parsing done, stats about the file
//!   { type: "triangulate_result", id, mesh }   — Triangulated BREP mesh data
//!   { type: "triangulate_error", id, name, error } — Triangulation failed for BREP
//!   { type: "all_complete", id, summary }      — All BREPs triangulated
//!   { type: "structure", id, tree }            — Assembly structure tree
//!   { type: "error", message }                 — General error

// State for the current STEP file being processed
let wasmExports = null;
let wasmInitialized = false;
let currentParseResult = null;   // Parsed STEP data (kept in WASM memory)
let pendingBreps = [];           // Array of pending BREP descriptors
let triangulatedCount = 0;
let totalBrepCount = 0;
let assemblyTree = null;
let requestId = 0;               // ID of the current request (to handle cancellation)

// ─── WASM Initialization ───────────────────────────────────────────────
//
// The worker loads the same WASM module as the main thread.
// Since Trunk builds the WASM with wasm-bindgen, we need to:
// 1. Import the JS glue code generated by wasm-bindgen
// 2. Call the init function to instantiate the WASM module
// 3. Access exported Rust functions via the wasmExports object

async function initWasm() {
    try {
        // Resolve the WASM module path relative to this worker script.
        const baseUrl = self.location.href.replace(/\/worker\.js$/, '/');
        const wasmJsUrl = baseUrl + 'draper_viewer.js';

        // Import the wasm-bindgen generated JS glue
        const module = await import(wasmJsUrl);

        // Initialize the WASM module — the default export handles
        // fetching and compiling the .wasm binary.
        if (module.default) {
            await module.default();
        }

        wasmExports = module;
        wasmInitialized = true;

        // Verify that the worker exports are available
        if (!wasmExports.worker_parse_step || !wasmExports.worker_triangulate_brep) {
            console.error('[3Draper Worker] Required WASM exports not found: worker_parse_step, worker_triangulate_brep');
            self.postMessage({
                type: 'error',
                message: 'Worker WASM exports not available. Falling back to main-thread processing.'
            });
            return;
        }

        self.postMessage({ type: 'ready' });
        console.log('[3Draper Worker] WASM initialized successfully — worker exports available');
    } catch (err) {
        console.error('[3Draper Worker] WASM initialization failed:', err);
        self.postMessage({
            type: 'error',
            message: `WASM init failed: ${err.message}. ` +
                     'The worker cannot load the WASM module. Falling back to main-thread processing.'
        });
    }
}

// Start initialization immediately on worker startup
initWasm();

// ─── Message Handler ───────────────────────────────────────────────────

self.onmessage = async function(e) {
    const msg = e.data;

    if (!wasmInitialized && msg.type !== 'init') {
        self.postMessage({ type: 'error', message: 'Worker not initialized yet' });
        return;
    }

    switch (msg.type) {
        case 'init':
            if (!wasmInitialized) {
                await initWasm();
            }
            break;

        case 'parse':
            handleParse(msg);
            break;

        case 'triangulate_next':
            handleTriangulateNext(msg);
            break;

        case 'cancel':
            handleCancel();
            break;

        case 'get_structure':
            handleGetStructure(msg);
            break;

        default:
            console.warn('[3Draper Worker] Unknown message type:', msg.type);
    }
};

// ─── STEP Parsing ──────────────────────────────────────────────────────

function handleParse(msg) {
    const { id, content, name, lod, is_mobile } = msg;
    requestId = id;

    try {
        // Call the Rust worker_parse_step function via wasm-bindgen.
        // This parses the STEP file, extracts the assembly tree and pending
        // BREP descriptors, and stores the result in thread-local state.
        const lodValue = lod || 1.0;
        const isMobile = is_mobile || false;
        const result = wasmExports.worker_parse_step(content, name || 'unknown.stp', lodValue, isMobile);

        if (result.error && result.error.length > 0) {
            self.postMessage({
                type: 'error',
                message: `STEP parse error: ${result.error}`
            });
            return;
        }

        // Parse the pending BREP descriptors from JSON
        try {
            pendingBreps = JSON.parse(result.pending_breps_json);
        } catch (e) {
            pendingBreps = [];
        }

        // Parse the assembly tree from JSON
        try {
            assemblyTree = JSON.parse(result.assembly_tree_json);
        } catch (e) {
            assemblyTree = null;
        }

        totalBrepCount = pendingBreps.length;
        triangulatedCount = 0;
        currentParseResult = result;

        self.postMessage({
            type: 'parse_complete',
            id: id,
            stats: {
                name: name,
                entity_count: result.entity_count,
                face_count: result.face_count,
                brep_count: totalBrepCount,
                shell_count: result.shell_count,
            }
        });

    } catch (err) {
        console.error('[3Draper Worker] Parse error:', err);
        self.postMessage({
            type: 'error',
            message: `Parse failed: ${err.message}`
        });
    }
}

// ─── Triangulation ─────────────────────────────────────────────────────

function handleTriangulateNext(msg) {
    if (pendingBreps.length === 0) {
        self.postMessage({
            type: 'all_complete',
            id: requestId,
            summary: {
                triangulated: triangulatedCount,
                total: totalBrepCount,
            }
        });
        return;
    }

    const brep = pendingBreps.shift();

    try {
        const startTime = performance.now();

        // Call the Rust worker_triangulate_brep function via wasm-bindgen.
        // This triangulates the next pending BREP and returns flat mesh data.
        const meshData = wasmExports.worker_triangulate_brep();
        const elapsed = performance.now() - startTime;

        if (meshData.error && meshData.error.length > 0) {
            triangulatedCount++;
            self.postMessage({
                type: 'triangulate_error',
                id: requestId,
                name: meshData.name || brep.name,
                brep_id: meshData.brep_id || brep.brep_id,
                error: meshData.error,
                progress: {
                    completed: triangulatedCount,
                    total: totalBrepCount,
                }
            });
        } else if (meshData.vertices.length > 0 && meshData.indices.length > 0) {
            triangulatedCount++;

            // Convert flat arrays to TypedArrays for efficient transfer
            const vertices = new Float32Array(meshData.vertices);
            const indices = new Uint32Array(meshData.indices);
            const normals = meshData.normals.length > 0 ? new Float32Array(meshData.normals) : null;
            const faceNormals = meshData.face_normals.length > 0 ? new Float32Array(meshData.face_normals) : null;
            const colors = meshData.colors.length > 0 ? new Float32Array(meshData.colors) : null;

            const resultMesh = {
                name: meshData.name,
                brep_id: meshData.brep_id,
                color: meshData.color.length > 0 ? meshData.color : (brep.color || null),
                vertex_count: vertices.length / 3,
                triangle_count: indices.length / 3,
                vertices: vertices,
                indices: indices,
                normals: normals,
                face_normals: faceNormals,
                colors: colors,
            };

            self.postMessage({
                type: 'triangulate_result',
                id: requestId,
                mesh: resultMesh,
                brep_id: meshData.brep_id,
                name: meshData.name,
                color: resultMesh.color,
                elapsed_ms: elapsed,
                progress: {
                    completed: triangulatedCount,
                    total: totalBrepCount,
                }
            }, getTransferables(resultMesh));
        } else {
            // Empty mesh produced
            triangulatedCount++;
            self.postMessage({
                type: 'triangulate_error',
                id: requestId,
                name: meshData.name || brep.name,
                brep_id: meshData.brep_id || brep.brep_id,
                error: 'Empty mesh produced',
                progress: {
                    completed: triangulatedCount,
                    total: totalBrepCount,
                }
            });
        }
    } catch (err) {
        console.error('[3Draper Worker] Triangulation error:', err);
        triangulatedCount++;
        self.postMessage({
            type: 'triangulate_error',
            id: requestId,
            name: brep.name || 'unknown',
            brep_id: brep.brep_id,
            error: err.message,
            progress: {
                completed: triangulatedCount,
                total: totalBrepCount,
            }
        });
    }

    // Check if all done
    if (pendingBreps.length === 0) {
        self.postMessage({
            type: 'all_complete',
            id: requestId,
            summary: {
                triangulated: triangulatedCount,
                total: totalBrepCount,
            }
        });
    }
}

function handleCancel() {
    // Call the Rust cancel function to release WASM state
    if (wasmExports && wasmExports.worker_cancel) {
        try {
            wasmExports.worker_cancel();
        } catch (e) {
            console.warn('[3Draper Worker] Cancel error:', e);
        }
    }
    pendingBreps = [];
    currentParseResult = null;
    assemblyTree = null;
    triangulatedCount = 0;
    totalBrepCount = 0;
    requestId = 0;
}

function handleGetStructure(msg) {
    let treeJson = '{}';
    if (wasmExports && wasmExports.worker_get_assembly_tree) {
        try {
            treeJson = wasmExports.worker_get_assembly_tree();
        } catch (e) {
            console.warn('[3Draper Worker] Get structure error:', e);
        }
    }
    let tree = assemblyTree;
    try {
        tree = JSON.parse(treeJson);
    } catch (e) {}
    self.postMessage({
        type: 'structure',
        id: msg.id,
        tree: tree,
    });
}

// ─── Transferable Objects ──────────────────────────────────────────────
//
// Use transferable ArrayBuffers for zero-copy mesh data transfer.
// When an ArrayBuffer is transferred, the sender loses access to it,
// but the receiver gets it instantly without copying.

function getTransferables(meshData) {
    const transferables = [];
    if (meshData.vertices instanceof Float32Array && meshData.vertices.buffer) {
        transferables.push(meshData.vertices.buffer);
    }
    if (meshData.indices instanceof Uint32Array && meshData.indices.buffer) {
        transferables.push(meshData.indices.buffer);
    }
    if (meshData.normals instanceof Float32Array && meshData.normals && meshData.normals.buffer) {
        transferables.push(meshData.normals.buffer);
    }
    if (meshData.colors instanceof Float32Array && meshData.colors && meshData.colors.buffer) {
        transferables.push(meshData.colors.buffer);
    }
    return transferables;
}
