//! Build script for generating C header file from FFI definitions.
//! Only generates headers on native targets (not wasm).

fn main() {
    #[cfg(not(target_arch = "wasm32"))]
    {
        let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();

        let config = cbindgen::Config {
            language: cbindgen::Language::C,
            include_guard: Some("DRAPER_H".to_string()),
            autogen_warning: Some("/* Warning: this file is auto-generated by cbindgen. Do not modify. */".to_string()),
            ..Default::default()
        };

        if let Ok(bindings) = cbindgen::Builder::new()
            .with_crate(crate_dir.as_str())
            .with_config(config)
            .generate()
        {
            let out_path = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
            let include_dir = out_path.parent().unwrap().parent().unwrap().join("include");
            std::fs::create_dir_all(&include_dir).ok();
            bindings.write_to_file(include_dir.join("draper.h"));
        }
    }
}
