// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 KernelDev
//! Macro Recorder — Phase 3.3.
//!
//! Records user actions into a list that can be replayed or exported
//! as a Python/Lua script.

use std::time::Instant;

thread_local! {
    pub static DIALOG_RECORDER: std::cell::RefCell<MacroRecorder> =
        std::cell::RefCell::new(MacroRecorder::new());
    pub static DIALOG_MACRO_NAME: std::cell::RefCell<String> =
        std::cell::RefCell::new(String::from("macro1"));
    pub static DIALOG_MACRO_LANG: std::cell::Cell<u8> = const { std::cell::Cell::new(0) };
    pub static DIALOG_EXPORT_TEXT: std::cell::RefCell<String> =
        std::cell::RefCell::new(String::new());
}

pub fn sync_to_dialog(recorder: &MacroRecorder) {
    DIALOG_RECORDER.with(|r| *r.borrow_mut() = recorder.clone());
}

pub fn sync_from_dialog(recorder: &mut MacroRecorder) {
    *recorder = DIALOG_RECORDER.with(|r| r.borrow().clone());
}

#[derive(Clone, Debug, PartialEq)]
pub struct RecordedAction {
    pub timestamp_ms: u64,
    pub action: String,
    pub arg: Option<String>,
    pub value: Option<f64>,
}

#[derive(Clone, Debug)]
pub struct MacroRecorder {
    pub recording: bool,
    pub replaying: bool,
    pub actions: Vec<RecordedAction>,
    start_time: Option<Instant>,
    pub replay_delay_ms: u64,
}

impl Default for MacroRecorder {
    fn default() -> Self { Self::new() }
}

impl MacroRecorder {
    pub fn new() -> Self {
        Self {
            recording: false,
            replaying: false,
            actions: Vec::new(),
            start_time: None,
            replay_delay_ms: 0,
        }
    }

    pub fn start(&mut self) {
        self.actions.clear();
        self.recording = true;
        self.start_time = Some(Instant::now());
    }

    pub fn stop(&mut self) -> usize {
        self.recording = false;
        self.start_time = None;
        self.actions.len()
    }

    pub fn record(&mut self, action: &str) {
        if !self.recording { return; }
        let ts = self.elapsed_ms();
        self.actions.push(RecordedAction {
            timestamp_ms: ts, action: action.to_string(), arg: None, value: None,
        });
    }

    pub fn record_with_arg(&mut self, action: &str, arg: &str) {
        if !self.recording { return; }
        let ts = self.elapsed_ms();
        self.actions.push(RecordedAction {
            timestamp_ms: ts, action: action.to_string(),
            arg: Some(arg.to_string()), value: None,
        });
    }

    pub fn record_with_value(&mut self, action: &str, arg: &str, value: f64) {
        if !self.recording { return; }
        let ts = self.elapsed_ms();
        self.actions.push(RecordedAction {
            timestamp_ms: ts, action: action.to_string(),
            arg: Some(arg.to_string()), value: Some(value),
        });
    }

    pub fn clear(&mut self) { self.actions.clear(); }
    pub fn len(&self) -> usize { self.actions.len() }
    pub fn is_empty(&self) -> bool { self.actions.is_empty() }

    fn elapsed_ms(&self) -> u64 {
        match self.start_time {
            Some(t) => t.elapsed().as_millis() as u64,
            None => 0,
        }
    }

    pub fn export_python(&self, macro_name: &str) -> String {
        let mut out = String::new();
        out.push_str("#!/usr/bin/env python3\n");
        out.push_str(&format!("# BRepCAD macro: {}\n", macro_name));
        out.push_str(&format!("# Recorded actions: {}\n", self.actions.len()));
        out.push_str("# Generated by BRepCAD Macro Recorder\n\n");
        out.push_str("import BRepCAD\n\n");
        out.push_str("def main():\n");
        out.push_str("    app = BRepCAD.App()\n\n");
        for act in &self.actions {
            match (&act.arg, &act.value) {
                (Some(arg), Some(val)) => out.push_str(&format!(
                    "    app.set_param(\"{}\", {:.6})  # t={:.3}s\n",
                    arg, val, act.timestamp_ms as f64 / 1000.0)),
                (Some(arg), None) => out.push_str(&format!(
                    "    app.action(\"{}\", \"{}\")  # t={:.3}s\n",
                    act.action, arg, act.timestamp_ms as f64 / 1000.0)),
                _ => out.push_str(&format!(
                    "    app.action(\"{}\")  # t={:.3}s\n",
                    act.action, act.timestamp_ms as f64 / 1000.0)),
            }
        }
        out.push_str("\nif __name__ == \"__main__\":\n    main()\n");
        out
    }

    pub fn export_lua(&self, macro_name: &str) -> String {
        let mut out = String::new();
        out.push_str(&format!("-- BRepCAD macro: {}\n", macro_name));
        out.push_str(&format!("-- Recorded actions: {}\n", self.actions.len()));
        out.push_str("-- Generated by BRepCAD Macro Recorder\n\n");
        out.push_str("local BRepCAD = require(\"BRepCAD\")\n");
        out.push_str("local app = BRepCAD.App.new()\n\n");
        for act in &self.actions {
            match (&act.arg, &act.value) {
                (Some(arg), Some(val)) => out.push_str(&format!(
                    "app:set_param(\"{}\", {:.6})  -- t={:.3}s\n",
                    arg, val, act.timestamp_ms as f64 / 1000.0)),
                (Some(arg), None) => out.push_str(&format!(
                    "app:action(\"{}\", \"{}\")  -- t={:.3}s\n",
                    act.action, arg, act.timestamp_ms as f64 / 1000.0)),
                _ => out.push_str(&format!(
                    "app:action(\"{}\")  -- t={:.3}s\n",
                    act.action, act.timestamp_ms as f64 / 1000.0)),
            }
        }
        out
    }

    pub fn descriptions(&self) -> Vec<String> {
        self.actions.iter().enumerate().map(|(i, a)| {
            let ts = a.timestamp_ms as f64 / 1000.0;
            match (&a.arg, &a.value) {
                (Some(arg), Some(val)) => format!("{}. [{:06.3}] {}: {} = {:.4}", i + 1, ts, a.action, arg, val),
                (Some(arg), None) => format!("{}. [{:06.3}] {}: {}", i + 1, ts, a.action, arg),
                _ => format!("{}. [{:06.3}] {}", i + 1, ts, a.action),
            }
        }).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_recorder_default() {
        let r = MacroRecorder::new();
        assert!(!r.recording);
        assert!(r.is_empty());
    }

    #[test]
    fn test_start_stop() {
        let mut r = MacroRecorder::new();
        r.start();
        assert!(r.recording);
        r.record("InsertBox");
        r.record("ViewIso");
        let n = r.stop();
        assert!(!r.recording);
        assert_eq!(n, 2);
    }

    #[test]
    fn test_record_noop_when_not_recording() {
        let mut r = MacroRecorder::new();
        r.record("InsertBox");
        assert!(r.is_empty());
    }

    #[test]
    fn test_record_with_arg() {
        let mut r = MacroRecorder::new();
        r.start();
        r.record_with_arg("EditCut", "sel1");
        assert_eq!(r.len(), 1);
        assert_eq!(r.actions[0].arg.as_deref(), Some("sel1"));
    }

    #[test]
    fn test_record_with_value() {
        let mut r = MacroRecorder::new();
        r.start();
        r.record_with_value("SetParam", "width", 100.0);
        assert_eq!(r.actions[0].value, Some(100.0));
    }

    #[test]
    fn test_export_python() {
        let mut r = MacroRecorder::new();
        r.start();
        r.record("InsertBox");
        r.record_with_value("SetParam", "width", 100.0);
        r.record_with_arg("EditCut", "sel1");
        r.stop();
        let py = r.export_python("test");
        assert!(py.contains("#!/usr/bin/env python3"));
        assert!(py.contains("import BRepCAD"));
        assert!(py.contains("app.action(\"InsertBox\")"));
        assert!(py.contains("app.set_param(\"width\", 100.000000)"));
        assert!(py.contains("app.action(\"EditCut\", \"sel1\")"));
    }

    #[test]
    fn test_export_lua() {
        let mut r = MacroRecorder::new();
        r.start();
        r.record("InsertBox");
        r.record_with_value("SetParam", "width", 100.0);
        r.stop();
        let lua = r.export_lua("test");
        assert!(lua.contains("require(\"BRepCAD\")"));
        assert!(lua.contains("app:action(\"InsertBox\")"));
        assert!(lua.contains("app:set_param(\"width\", 100.000000)"));
    }

    #[test]
    fn test_descriptions() {
        let mut r = MacroRecorder::new();
        r.start();
        r.record("InsertBox");
        r.record_with_value("SetParam", "width", 42.5);
        r.stop();
        let d = r.descriptions();
        assert_eq!(d.len(), 2);
        assert!(d[0].contains("InsertBox"));
        assert!(d[1].contains("width"));
        assert!(d[1].contains("42.5"));
    }

    #[test]
    fn test_start_clears_previous() {
        let mut r = MacroRecorder::new();
        r.start();
        r.record("A");
        r.record("B");
        r.stop();
        assert_eq!(r.len(), 2);
        r.start();
        assert!(r.is_empty());
    }
}
