// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 KernelDev
//
// JavaScript bindings for the 3Draper kernel.
//
// This module provides two integration paths:
//
// 1. **Emscripten / WASM** — when the 3Draper library is compiled to
//    WebAssembly via `wasm-bindgen`, this module wraps the generated
//    WASM exports as a friendly JavaScript API.
//
// 2. **Node.js native addon** — when the shared library is available
//    as a native Node addon (via `ffi-napi` or a custom N-API module),
//    this module provides the same API surface.
//
// Currently this file documents the *intended* public API.  Concrete
// WASM exports will be generated by `wasm-bindgen` once the crate is
// configured for `wasm32-unknown-unknown`.  Until then, the stub
// implementations below throw descriptive errors.

"use strict";

// ============================================================
// Error codes (must match DraperResult in lib.rs)
// ============================================================

const DraperResult = Object.freeze({
  SUCCESS:              0,
  INVALID_ARGUMENT:    -1,
  FILE_NOT_FOUND:      -2,
  PARSE_ERROR:         -3,
  GEOMETRY_ERROR:      -4,
  TOPOLOGY_ERROR:      -5,
  TRIANGULATION_ERROR: -6,
  OUT_OF_MEMORY:       -7,
  UNKNOWN_ERROR:      -99,
});

const RESULT_MESSAGES = {
  [DraperResult.SUCCESS]:              "Success",
  [DraperResult.INVALID_ARGUMENT]:     "Invalid argument",
  [DraperResult.FILE_NOT_FOUND]:      "File not found",
  [DraperResult.PARSE_ERROR]:         "Parse error",
  [DraperResult.GEOMETRY_ERROR]:      "Geometry error",
  [DraperResult.TOPOLOGY_ERROR]:      "Topology error",
  [DraperResult.TRIANGULATION_ERROR]: "Triangulation error",
  [DraperResult.OUT_OF_MEMORY]:       "Out of memory",
  [DraperResult.UNKNOWN_ERROR]:       "Unknown error",
};

// ============================================================
// DraperError
// ============================================================

class DraperError extends Error {
  /**
   * @param {number} code - DraperResult code
   * @param {string} [message] - Optional detail message
   */
  constructor(code, message) {
    const msg = message || RESULT_MESSAGES[code] || `Unknown code: ${code}`;
    super(`DraperError(${code}): ${msg}`);
    this.name = "DraperError";
    this.code = code;
  }
}

// ============================================================
// WASM binding stubs
//
// In a real WASM build, these would be populated by wasm-bindgen
// generated glue code.  For now they throw.
// ============================================================

let _wasm = null;

/**
 * Initialise the WASM module.
 *
 * @param {WebAssembly.Module|object} wasmModule - The compiled WASM module
 *   or a wasm-bindgen-generated init object.
 */
async function init(wasmModule) {
  // In a real integration this would be:
  //   _wasm = await wasmBindgenInit(wasmModule);
  _wasm = wasmModule;
}

// ============================================================
// Version & feature detection
// ============================================================

/**
 * Returns the library version as a string (e.g. "0.1.0").
 * @returns {string}
 */
function version() {
  if (_wasm && _wasm.draper_version_string) {
    return _wasm.draper_version_string();
  }
  return "0.1.0"; // fallback — matches current native build
}

/**
 * Returns the library version as [major, minor, patch].
 * @returns {number[]}
 */
function versionTuple() {
  if (_wasm && _wasm.draper_version_major) {
    return [
      _wasm.draper_version_major(),
      _wasm.draper_version_minor(),
      _wasm.draper_version_patch(),
    ];
  }
  return [0, 1, 0];
}

/**
 * Check whether the library supports a named feature.
 *
 * Feature names: step_import, step_export, stl_export, gltf_export,
 * obj_export, 3mf_export, boolean_ops, healing, validation,
 * analytical_queries, bvh.
 *
 * @param {string} feature
 * @returns {boolean}
 */
function hasFeature(feature) {
  if (_wasm && _wasm.draper_has_feature) {
    return _wasm.draper_has_feature(feature);
  }
  // Static fallback for known features
  const known = [
    "step_import", "step_export", "stl_export", "gltf_export",
    "obj_export", "3mf_export", "boolean_ops", "healing",
    "validation", "analytical_queries", "bvh",
  ];
  return known.includes(feature);
}

// ============================================================
// Document class
// ============================================================

class Document {
  /**
   * Create a new 3Draper document.
   * @param {string} [name="Untitled"]
   */
  constructor(name = "Untitled") {
    if (_wasm && _wasm.DraperDocument) {
      this._handle = _wasm.DraperDocument.new(name);
    } else {
      this._handle = null; // stub mode
    }
    this._name = name;
    this._solids = [];
  }

  // ----------------------------------------------------------
  // Shape builders
  // ----------------------------------------------------------

  /**
   * Add a box primitive.
   * @param {number} dx
   * @param {number} dy
   * @param {number} dz
   */
  addBox(dx, dy, dz) {
    if (this._handle) {
      const rc = this._handle.add_box(dx, dy, dz);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    } else {
      this._solids.push({ type: "box", dx, dy, dz });
    }
  }

  /**
   * Add a cylinder primitive.
   * @param {number} radius
   * @param {number} height
   */
  addCylinder(radius, height) {
    if (this._handle) {
      const rc = this._handle.add_cylinder(radius, height);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    } else {
      this._solids.push({ type: "cylinder", radius, height });
    }
  }

  /**
   * Add a sphere primitive.
   * @param {number} radius
   */
  addSphere(radius) {
    if (this._handle) {
      const rc = this._handle.add_sphere(radius);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    } else {
      this._solids.push({ type: "sphere", radius });
    }
  }

  /**
   * Add a cone primitive.
   * @param {number} radius
   * @param {number} height
   */
  addCone(radius, height) {
    if (this._handle) {
      const rc = this._handle.add_cone(radius, height);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    } else {
      this._solids.push({ type: "cone", radius, height });
    }
  }

  /**
   * Add a torus primitive.
   * @param {number} majorRadius
   * @param {number} minorRadius
   */
  addTorus(majorRadius, minorRadius) {
    if (this._handle) {
      const rc = this._handle.add_torus(majorRadius, minorRadius);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    } else {
      this._solids.push({ type: "torus", majorRadius, minorRadius });
    }
  }

  // ----------------------------------------------------------
  // Properties
  // ----------------------------------------------------------

  /** Number of solids in the document. */
  get solidCount() {
    if (this._handle) return this._handle.solid_count();
    return this._solids.length;
  }

  // ----------------------------------------------------------
  // Triangulation
  // ----------------------------------------------------------

  /**
   * Triangulate the document and return a Mesh object.
   * @returns {Mesh}
   */
  triangulate() {
    if (this._handle) {
      const meshHandle = this._handle.triangulate();
      return new Mesh(meshHandle);
    }
    throw new DraperError(
      DraperResult.TRIANGULATION_ERROR,
      "WASM module not loaded — triangulation unavailable"
    );
  }

  // ----------------------------------------------------------
  // Analytical queries
  // ----------------------------------------------------------

  /** Compute total volume of all solids. */
  volume() {
    if (this._handle) return this._handle.solid_volume();
    return 0.0;
  }

  /** Compute total surface area of all solids. */
  surfaceArea() {
    if (this._handle) return this._handle.solid_surface_area();
    return 0.0;
  }

  // ----------------------------------------------------------
  // Validation
  // ----------------------------------------------------------

  /**
   * Run topology validation.  Throws DraperError on failure.
   */
  validate() {
    if (this._handle) {
      const rc = this._handle.validate_step();
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    }
  }

  // ----------------------------------------------------------
  // Export
  // ----------------------------------------------------------

  /**
   * Export to STEP format.
   * @param {string} path
   */
  exportStep(path) {
    if (this._handle) {
      const rc = this._handle.export_step(path);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    }
  }

  /**
   * Export to glTF 2.0 (GLB binary).
   * @param {string} path
   */
  exportGltf(path) {
    if (this._handle) {
      const rc = this._handle.export_gltf(path);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    }
  }

  /**
   * Export to Wavefront OBJ.
   * @param {string} path
   */
  exportObj(path) {
    if (this._handle) {
      const rc = this._handle.export_obj(path);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    }
  }

  /**
   * Export to 3MF.
   * @param {string} path
   */
  export3mf(path) {
    if (this._handle) {
      const rc = this._handle.export_3mf(path);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    }
  }

  // ----------------------------------------------------------
  // Cleanup
  // ----------------------------------------------------------

  /** Free the underlying handle. */
  free() {
    if (this._handle) {
      this._handle.free();
      this._handle = null;
    }
  }
}

// ============================================================
// Mesh class
// ============================================================

class Mesh {
  constructor(handle) {
    this._handle = handle;
  }

  /** Number of vertices. */
  get vertexCount() {
    return this._handle ? this._handle.vertex_count() : 0;
  }

  /** Number of triangles. */
  get triangleCount() {
    return this._handle ? this._handle.triangle_count() : 0;
  }

  /**
   * Get vertex positions as a Float64Array (x,y,z triplets).
   * @returns {Float64Array}
   */
  getVertices() {
    if (!this._handle) return new Float64Array(0);
    return this._handle.get_vertices();
  }

  /**
   * Get triangle indices as a Uint32Array (i,j,k triplets).
   * @returns {Uint32Array}
   */
  getTriangles() {
    if (!this._handle) return new Uint32Array(0);
    return this._handle.get_triangles();
  }

  /**
   * Export mesh to STL.
   * @param {string} path
   * @param {boolean} [binary=true]
   */
  exportStl(path, binary = true) {
    if (this._handle) {
      const rc = this._handle.export_stl(path, binary);
      if (rc !== DraperResult.SUCCESS) throw new DraperError(rc);
    }
  }

  /** Free the mesh handle. */
  free() {
    if (this._handle) {
      this._handle.free();
      this._handle = null;
    }
  }
}

// ============================================================
// Exports
// ============================================================

module.exports = {
  // Classes
  Document,
  Mesh,
  DraperError,

  // Enums / constants
  DraperResult,

  // Functions
  init,
  version,
  versionTuple,
  hasFeature,
};
