#ifndef DRAPER_H
#define DRAPER_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a Document.
 */
typedef struct DraperDocument DraperDocument;

/**
 * Opaque handle to a TriangleMesh.
 */
typedef struct DraperMesh DraperMesh;

/**
 * Statistics about a document.
 */
typedef struct DraperStatistics {
  uint64_t vertex_count;
  uint64_t edge_count;
  uint64_t face_count;
  uint64_t solid_count;
  uint64_t triangle_count;
  uint64_t mesh_vertex_count;
} DraperStatistics;

/**
 * 3D point for FFI.
 */
typedef struct DraperVec3 {
  double x;
  double y;
  double z;
} DraperVec3;

/**
 * Create a new empty document.
 */
struct DraperDocument *draper_document_new(void);

/**
 * Open a STEP file.
 * Returns null on failure.
 */
struct DraperDocument *draper_open_step(const char *path);

/**
 * Save a document as a STEP file.
 * Returns 0 on success, -1 on failure.
 */
int32_t draper_save_step(struct DraperDocument *doc, const char *path);

/**
 * Get document statistics.
 */
struct DraperStatistics draper_get_statistics(const struct DraperDocument *doc);

/**
 * Free a document.
 */
void draper_document_free(struct DraperDocument *doc);

/**
 * Get the combined triangle mesh from the document.
 * The caller must free the mesh with draper_mesh_free().
 */
struct DraperMesh *draper_get_mesh(const struct DraperDocument *doc);

/**
 * Get the number of vertices in a mesh.
 */
uint64_t draper_mesh_vertex_count(const struct DraperMesh *mesh);

/**
 * Get the number of triangles in a mesh.
 */
uint64_t draper_mesh_triangle_count(const struct DraperMesh *mesh);

/**
 * Get a pointer to the vertex data.
 * Returns a pointer to an array of DraperVec3.
 * The pointer is valid as long as the mesh is alive.
 */
const struct DraperVec3 *draper_mesh_vertices(const struct DraperMesh *mesh);

/**
 * Get a pointer to the index data.
 * Returns a pointer to an array of u32 triangle indices.
 * The pointer is valid as long as the mesh is alive.
 */
const uint32_t *draper_mesh_indices(const struct DraperMesh *mesh);

/**
 * Get a pointer to the normal data (3 floats per vertex).
 * Returns null if normals are not computed.
 */
const float *draper_mesh_normals(const struct DraperMesh *mesh);

/**
 * Free a mesh.
 */
void draper_mesh_free(struct DraperMesh *mesh);

/**
 * Get the library version string.
 * The returned pointer is static and should not be freed.
 */
const char *draper_version(void);

#endif  /* DRAPER_H */
