#ifndef DRAPER_H
#define DRAPER_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque document handle.
 */
typedef struct DraperDocument DraperDocument;

/**
 * Opaque mesh handle.
 */
typedef struct DraperMesh DraperMesh;

/**
 * Create a new empty document.
 */
struct DraperDocument *draper_document_new(const char *name);

/**
 * Free a document.
 */
void draper_document_free(struct DraperDocument *doc);

/**
 * Add a box to the document.
 */
int32_t draper_document_add_box(struct DraperDocument *doc, double dx, double dy, double dz);

/**
 * Add a cylinder to the document.
 */
int32_t draper_document_add_cylinder(struct DraperDocument *doc, double radius, double height);

/**
 * Add a sphere to the document.
 */
int32_t draper_document_add_sphere(struct DraperDocument *doc, double radius);

/**
 * Add a cone to the document.
 */
int32_t draper_document_add_cone(struct DraperDocument *doc, double radius, double height);

/**
 * Add a torus to the document.
 */
int32_t draper_document_add_torus(struct DraperDocument *doc,
                                  double major_radius,
                                  double minor_radius);

/**
 * Build an ICE engine model.
 */
int32_t draper_document_add_engine(struct DraperDocument *doc);

/**
 * Triangulate the document and return a mesh.
 */
struct DraperMesh *draper_document_triangulate(struct DraperDocument *doc);

/**
 * Free a mesh.
 */
void draper_mesh_free(struct DraperMesh *mesh);

/**
 * Get mesh vertex count.
 */
uint32_t draper_mesh_vertex_count(const struct DraperMesh *mesh);

/**
 * Get mesh triangle count.
 */
uint32_t draper_mesh_triangle_count(const struct DraperMesh *mesh);

/**
 * Get mesh vertex data (x, y, z triplets).
 * Caller must allocate buffer of size vertex_count * 3.
 */
uint32_t draper_mesh_get_vertices(const struct DraperMesh *mesh, double *out, uint32_t max_count);

/**
 * Get mesh triangle indices (i, j, k triplets).
 * Caller must allocate buffer of size triangle_count * 3.
 */
uint32_t draper_mesh_get_triangles(const struct DraperMesh *mesh,
                                   uint32_t *out,
                                   uint32_t max_count);

/**
 * Export mesh to STL file.
 */
int32_t draper_mesh_export_stl(const struct DraperMesh *mesh, const char *path, int32_t binary);

/**
 * Export document to STEP file.
 */
int32_t draper_document_export_step(struct DraperDocument *doc, const char *path);

/**
 * Get the number of solids in the document.
 */
uint32_t draper_document_solid_count(const struct DraperDocument *doc);

#endif  /* DRAPER_H */
