// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 KernelDev
//! Web Worker for offloading STEP parsing and triangulation from the main thread.
//!
//! This worker runs the heavy computational tasks (STEP file parsing, B-Rep
//! triangulation, mesh generation) in a background thread, keeping the main
//! thread free for UI rendering at 60+ FPS.
//!
//! # Architecture
//!
//! Main Thread (UI):
//!   - Handles user input, egui/wgpu rendering
//!   - Sends STEP file content to worker via postMessage
//!   - Receives triangulated mesh data back via onmessage
//!
//! Worker Thread:
//!   - Initializes WASM module on startup
//!   - Parses STEP files into B-Rep topology
//!   - Triangulates B-Reps one at a time (chunked)
//!   - Sends completed mesh vertices/indices back to main thread
//!
//! # Message Protocol
//!
//! Main → Worker:
//!   { type: "init" }                           — Initialize WASM (auto-sent on worker start)
//!   { type: "parse", id, content, name }       — Parse STEP file content
//!   { type: "triangulate_next", id }           — Triangulate next pending BREP
//!   { type: "cancel" }                         — Cancel current processing
//!   { type: "get_structure", id }              — Get assembly structure tree
//!
//! Worker → Main:
//!   { type: "ready" }                          — Worker initialized and ready
//!   { type: "parse_complete", id, stats }      — STEP parsing done, stats about the file
//!   { type: "triangulate_result", id, mesh }   — Triangulated BREP mesh data
//!   { type: "triangulate_error", id, name, error } — Triangulation failed for BREP
//!   { type: "all_complete", id, summary }      — All BREPs triangulated
//!   { type: "structure", id, tree }            — Assembly structure tree
//!   { type: "error", message }                 — General error

// State for the current STEP file being processed
let wasmExports = null;
let wasmInitialized = false;
let currentParseResult = null;   // Parsed STEP data (kept in WASM memory)
let pendingBreps = [];           // Array of pending BREP descriptors
let triangulatedCount = 0;
let totalBrepCount = 0;
let assemblyTree = null;
let requestId = 0;               // ID of the current request (to handle cancellation)
let stepFilePtr = null;          // WASM pointer to StepFile (for Rust-side processing)

// ─── WASM Initialization ───────────────────────────────────────────────
//
// The worker loads the same WASM module as the main thread.
// Since Trunk builds the WASM with wasm-bindgen, we need to:
// 1. Import the JS glue code generated by wasm-bindgen
// 2. Call the init function to instantiate the WASM module
// 3. Access exported Rust functions via the wasmExports object
//
// IMPORTANT: The worker loads the WASM from the same URL as the main page,
// resolving the .js glue path relative to the worker's location.

async function initWasm() {
    try {
        // Resolve the WASM module path relative to this worker script.
        // Trunk places the output in the same directory as the HTML page.
        const baseUrl = self.location.href.replace(/\/worker\.js$/, '/');
        const wasmJsUrl = baseUrl + 'draper_viewer.js';

        // Import the wasm-bindgen generated JS glue
        const module = await import(wasmJsUrl);

        // Initialize the WASM module — the default export handles
        // fetching and compiling the .wasm binary
        if (module.default) {
            await module.default();
        }

        wasmExports = module;
        wasmInitialized = true;

        self.postMessage({ type: 'ready' });
        console.log('[3Draper Worker] WASM initialized successfully');
    } catch (err) {
        console.error('[3Draper Worker] WASM initialization failed:', err);
        self.postMessage({
            type: 'error',
            message: `WASM init failed: ${err.message}. ` +
                     'The worker cannot load the WASM module. Falling back to main-thread processing.'
        });
    }
}

// Start initialization immediately on worker startup
initWasm();

// ─── Message Handler ───────────────────────────────────────────────────

self.onmessage = async function(e) {
    const msg = e.data;

    if (!wasmInitialized && msg.type !== 'init') {
        self.postMessage({ type: 'error', message: 'Worker not initialized yet' });
        return;
    }

    switch (msg.type) {
        case 'init':
            // Already initialized above; if not, try again
            if (!wasmInitialized) {
                await initWasm();
            }
            break;

        case 'parse':
            handleParse(msg);
            break;

        case 'triangulate_next':
            handleTriangulateNext(msg);
            break;

        case 'triangulate_batch':
            handleTriangulateBatch(msg);
            break;

        case 'cancel':
            handleCancel();
            break;

        case 'get_structure':
            handleGetStructure(msg);
            break;

        default:
            console.warn('[3Draper Worker] Unknown message type:', msg.type);
    }
};

// ─── STEP Parsing ──────────────────────────────────────────────────────
//
// The STEP parsing happens entirely in WASM (Rust code). The worker
// sends the file content to the Rust parse_step function and receives
// back a structured result with:
//   - Entity counts (faces, breps, shells, etc.)
//   - Pending BREP descriptors (for progressive triangulation)
//   - Assembly tree structure
//
// NOTE: Full wasm-bindgen exports for parse_step and triangulate_brep
// are not yet implemented (Phase 1.3 WIP). The worker framework is
// in place, but actual computation currently falls back to the main thread.
// When the wasm-bindgen API is complete, this worker will automatically
// take over the heavy lifting.

function handleParse(msg) {
    const { id, content, name } = msg;
    requestId = id;

    try {
        // Check if the WASM module exports the parse_step function
        if (!wasmExports || !wasmExports.parse_step_worker) {
            // Fallback: return an error indicating main-thread processing needed
            self.postMessage({
                type: 'error',
                message: 'STEP parsing in worker requires wasm-bindgen exports (Phase 1.3 WIP). ' +
                         'Using main-thread fallback for now.'
            });
            return;
        }

        // Call the Rust parse_step function via wasm-bindgen
        const result = wasmExports.parse_step_worker(content);

        if (result.error) {
            self.postMessage({
                type: 'error',
                message: `STEP parse error: ${result.error}`
            });
            return;
        }

        // Store parsed state for progressive triangulation
        currentParseResult = result;
        pendingBreps = result.pending_breps || [];
        assemblyTree = result.assembly_tree || null;
        totalBrepCount = pendingBreps.length;
        triangulatedCount = 0;

        self.postMessage({
            type: 'parse_complete',
            id: id,
            stats: {
                name: name,
                entity_count: result.entity_count || 0,
                face_count: result.face_count || 0,
                brep_count: totalBrepCount,
                shell_count: result.shell_count || 0,
            }
        });

    } catch (err) {
        console.error('[3Draper Worker] Parse error:', err);
        self.postMessage({
            type: 'error',
            message: `Parse failed: ${err.message}`
        });
    }
}

// ─── Triangulation ─────────────────────────────────────────────────────
//
// Progressive triangulation: process one BREP at a time, sending
// the resulting mesh data back to the main thread for rendering.
// This keeps the worker responsive and allows the UI to show progress.

function handleTriangulateNext(msg) {
    if (pendingBreps.length === 0) {
        self.postMessage({
            type: 'all_complete',
            id: requestId,
            summary: {
                triangulated: triangulatedCount,
                total: totalBrepCount,
            }
        });
        return;
    }

    const brep = pendingBreps.shift();

    try {
        const startTime = performance.now();

        // Call the Rust triangulate_brep function via wasm-bindgen
        const meshData = wasmExports.triangulate_brep_worker(
            currentParseResult.step_file,
            brep.brep_id,
            brep.name,
            brep.transform
        );
        const elapsed = performance.now() - startTime;

        if (meshData && meshData.vertex_count > 0) {
            triangulatedCount++;
            self.postMessage({
                type: 'triangulate_result',
                id: requestId,
                mesh: meshData,
                brep_id: brep.brep_id,
                name: brep.name,
                color: brep.color,
                elapsed_ms: elapsed,
                progress: {
                    completed: triangulatedCount,
                    total: totalBrepCount,
                }
            }, getTransferables(meshData));
        } else {
            triangulatedCount++;
            self.postMessage({
                type: 'triangulate_error',
                id: requestId,
                name: brep.name,
                brep_id: brep.brep_id,
                error: 'Empty mesh produced',
                progress: {
                    completed: triangulatedCount,
                    total: totalBrepCount,
                }
            });
        }
    } catch (err) {
        console.error('[3Draper Worker] Triangulation error:', err);
        triangulatedCount++;
        self.postMessage({
            type: 'triangulate_error',
            id: requestId,
            name: brep.name,
            brep_id: brep.brep_id,
            error: err.message,
            progress: {
                completed: triangulatedCount,
                total: totalBrepCount,
            }
        });
    }

    // Check if all done
    if (pendingBreps.length === 0) {
        self.postMessage({
            type: 'all_complete',
            id: requestId,
            summary: {
                triangulated: triangulatedCount,
                total: totalBrepCount,
            }
        });
    }
}

function handleTriangulateBatch(msg) {
    const { max_count } = msg;
    let count = 0;

    while (pendingBreps.length > 0 && count < (max_count || 1)) {
        handleTriangulateNext(msg);
        count++;
    }
}

function handleCancel() {
    pendingBreps = [];
    currentParseResult = null;
    assemblyTree = null;
    triangulatedCount = 0;
    totalBrepCount = 0;
    requestId = 0;
}

function handleGetStructure(msg) {
    self.postMessage({
        type: 'structure',
        id: msg.id,
        tree: assemblyTree,
    });
}

// ─── Transferable Objects ──────────────────────────────────────────────
//
// Use transferable ArrayBuffers for zero-copy mesh data transfer.
// When an ArrayBuffer is transferred, the sender loses access to it,
// but the receiver gets it instantly without copying.

function getTransferables(meshData) {
    const transferables = [];
    if (meshData.vertices instanceof Float32Array && meshData.vertices.buffer) {
        transferables.push(meshData.vertices.buffer);
    }
    if (meshData.indices instanceof Uint32Array && meshData.indices.buffer) {
        transferables.push(meshData.indices.buffer);
    }
    if (meshData.normals instanceof Float32Array && meshData.normals && meshData.normals.buffer) {
        transferables.push(meshData.normals.buffer);
    }
    if (meshData.colors instanceof Float32Array && meshData.colors && meshData.colors.buffer) {
        transferables.push(meshData.colors.buffer);
    }
    return transferables;
}
